export enum UploadFileErrorEnum {
  FILE_MAX_SIZE = 'FILE_MAX_SIZE',
  FILE_MIN_SIZE = 'FILE_MIN_SIZE',
  FILE_EXTENSION = 'FILE_EXTENSION',
  FILE_MAX_AMOUNT = 'FILE_MAX_AMOUNT',
  FILE_MIN_AMOUNT = 'FILE_MIN_AMOUNT',
}
